sudo: false
language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g grunt-cli
script:
  karma start --single-run

