environment:
  matrix:
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "3"
    - nodejs_version: "2"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install

test_script:
  - node --version
  - npm --version
  - grunt
  - npm test
